#!/bin/sh
#
# Make regression-test loads for the CUPL compiler front end
#
TESTLOADS="cubic fancyquad poly11 power prime quadratic random rise simplequad squares sum"

trap "rm -f testcupl$$; exit 0"

rm -f *.test

for x in $TESTLOADS
do
	echo "Making ${x}.test from ${x}.cupl..."
	../cupl -v1 ${x}.cupl >${x}.test 2>&1
done

chmod -w *.test

echo "Done"

# regress ends here

