#!/bin/sh
#
# Regression-test the CUPL compiler front end
#
TESTLOADS="cubic fancyquad poly11 power prime quadratic random rise simplequad squares sum"

trap "rm -f testcupl$$; exit 0"

for x in $TESTLOADS
do
	echo "Testing against ${x}.cupl..."
	../cupl -v1 ${x}.cupl >testcupl$$
	diff -c ${x}.parse testcupl$$
done
echo "Done"

# regress ends here

